apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: nginx-deployment
  namespace: test-federation
spec:
  template:
    spec:
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.21
  placement:
    clusters:
    - name: mycluster1
    - name: mycluster2
  overrides:
  - clusterName: mycluster2
    clusterOverrides:
    - path: "/spec/replicas"
      value: 5
  - clusterName: mycluster1
    clusterOverrides:
    - path: "/spec/replicas"
      value: 3